### ISSUE TITLE
429 Too Many Requests Error

### ISSUE THREAD

**Issue by nonfungiblelaw** [a16z/nft-analyst-starter-pack#14]
When running export.py, I am now getting an error in the form of 'HTTPError: 429 Client Error:  too Many Requests for url: https://eth-mainnet.alchemyapi.io/v2/[my api key]'

I've only started getting this error over the last couple of days.  Prior to this, export.py was working well.  I'm wondering if others are getting this error, and if you have any suggestions.  Thanks.

**Comment by nonfungiblelaw** [comment]
Update:  I believe this issue was due to rate limiting by Alchemy for their free tier of service.  I tried to fix it by modifying the requests utility in the python Web3 module to progressively delay the request retries to Alchemy's service.  This did not solve the issue, and ultimately I solved it by just upgrading to a paid tier of Alchemy service :).

**Comment by emlazzarin** [comment]
I'm surprised you hit the rate limit — mind sharing any numbers from your Alchemy dash? Going to close this in the meantime.

**Comment by bodilyty** [comment]
I get 429 errors as well when running. export_data.py can still finish, but I've seen as high as 60% failure rate on the free alchemy subscription.
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/33468970/170077889-6403597f-ffc0-4b10-afe3-7d9cedcbd77b.png">

**Comment by ucw** [comment]
It seems that the rate limit did not work correctly, but now they have fixed it

**Comment by philipjames44** [comment]
I think this is a problem again. Getting rate limited with the free alchemy api key
