### ISSUE TITLE
429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by santoshi15** [a16z/nft-analyst-starter-pack#18]
I continue to get this error and the program ultimately ends before getting to any metadata creations.  I only need the metadata file to get rarity calculations; however, even if I comment out the transaction and sales functions within export_data.py and just start at `get_metadata_for_collection` it will generate a metadata csv without any rarity calculations

**Comment by jpzhangvincent** [comment]
I got the same error. I use the free tier of the Alchemy api. Does it matter?

**Comment by philipjames44** [comment]
+1, I think alchemy must've updated their rate limiting to be lower or smth.

**Comment by albeliakov** [comment]
Does anyone know how to fix?
