### ISSUE TITLE
export_data.py throws errors on the imports. Cannot run the script.

### ISSUE THREAD

**Issue by yarg-eth** [a16z/nft-analyst-starter-pack#7]
```
File "C:\Users\***NAME***\nft-analyst-starter-pack\export_data.py", line 14, in <module>
    import click

```
Does this for ethereumetl, numpy, pandas, ethereumetl.service.eth_service, and web3. I am using Python 3.9.12. I get that this is an error that I have created for myself, but do you know of any fixes off the top of your head?

**Comment by emlazzarin** [comment]
Are you running it via the appropriate poetry environment? Context is lacking.

**Comment by yarg-eth** [comment]
Turns out that I had to install poetry through Poetry's recommended way on their documentation. I spent hours and hours uninstalling and reinstalling through pip. After that, the venv was setup and there was no errors.

**Comment by emlazzarin** [comment]
Thanks for letting us know! Will add that to the docs.
